version: '3.8'
services:
  bachhoasi-api-user:
    container_name: bachhoasi-api-user-management
    image: ${DOCKER_USERNAME}/bach-hoa-si-api-user:latest
    ports:
      - ${PORT}:${PORT}
    restart: always
    environment:
      DB_URL: postgresql-bachhoasi
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      PENV: ${PENV}
      PORT: ${PORT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      ACCESS_TOKEN_EXT: ${ACCESS_TOKEN_EXT}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      REFRESH_TOKEN_EXT: ${REFRESH_TOKEN_EXT}
      BASE_URL_API: ${BASE_URL_API}
      ORIGIN_ALLOWED: ${ORIGIN_ALLOWED}
      ZALO_CLIENT_SECRET: ${ZALO_CLIENT_SECRET}
      ZALO_CODE_VERIFY: ${ZALO_CODE_VERIFY}
      ZALO_APP_ID: ${ZALO_APP_ID}
    networks:
      - bachhoasi-networks

networks:
  bachhoasi-networks:
    name: bach-hoa-si-api-test_bachhoasi-networks
    external: true
  nginx_proxy_manager:
    name: nginx_proxy_manager_default
    external: true

