on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  bach-hoa-si-api-user-build:
    name: Build source code to Docker image
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build API image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/bach-hoa-si-api-user:latest .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/bach-hoa-si-api-user:latest

      - name: Run registry garbage collection
        run: doctl registry garbage-collection start --include-untagged-manifests --force
  
  staging-api-deploy:
    name: Deploy Staging API Manager To Google Service Server For Testing
    runs-on: arisa-deploy
    needs: bach-hoa-si-api-user-build
    env:

      DB_PORT: ${{secrets.DB_PORT}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_NAME: ${{secrets.DB_NAME}}

      PENV: staging

      ACCESS_TOKEN_KEY: ${{secrets.ACCESS_TOKEN_KEY}}
      ACCESS_TOKEN_EXT: ${{secrets.ACCESS_TOKEN_EXT}}
      REFRESH_TOKEN_KEY: ${{secrets.REFRESH_TOKEN_KEY}}
      REFRESH_TOKEN_EXT: ${{secrets.REFRESH_TOKEN_EXT}}

      PORT: ${{secrets.PORT}}
      BASE_URL_API: ${{secrets.BASE_URL_API}}
      ORIGIN_ALLOWED: ${{secrets.ORIGIN_ALLOWED}}
      
      ZALO_CLIENT_SECRET: ${{secrets.ZALO_CLIENT_SECRET}}
      ZALO_CODE_VERIFY: ${{secrets.ZALO_CODE_VERIFY}}
      ZALO_APP_ID: ${{secrets.ZALO_APP_ID}}
      ZALO_SECRET : ${{secrets.ZALO_PRIVATE_SECRET}}
      
      DOCKER_USERNAME: ${{ secrets.REGISTRY_NAME }}
    steps:
    - name: Checkout Develop
      uses: actions/checkout@v3

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Stop BachHoaSi API
      run: docker compose -f docker-compose.test.yaml -p bach-hoa-si-api-user down bachhoasi-api-user

    - name: Clean Old BachHoaSi Image
      run: docker rmi ${{ secrets.REGISTRY_NAME }}/bach-hoa-si-api-user:latest 
      continue-on-error: true

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Deploy API
      run: docker compose -f docker-compose.test.yaml -p bach-hoa-si-api-user up -d bachhoasi-api-user